---
app_name: todolist
ci_cd_namespace: demo-ccsd-cicd
dev_namespace: demo-ccsd-dev
test_namespace: demo-ccsd-test

build:
  NAME: '{{ app_name }}'
deploy:
  dev:
    PIPELINES_NAMESPACE: '{{ ci_cd_namespace }}'
    NAME: '{{ app_name }}'
    NAMESPACE: '{{ dev_namespace }}'
    DEPLOYER_USER: jenkins
    NODE_ENV: dev
  test:
    PIPELINES_NAMESPACE: '{{ ci_cd_namespace }}'
    NAME: '{{ app_name }}'
    NAMESPACE: '{{ test_namespace }}'
    DEPLOYER_USER: jenkins
    NODE_ENV: test

db:
  MONGODB_DATABASE: '{{ app_name }}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: todolist-build
        template: '{{ playbook_dir }}/templates/todolist-build.yml'
        params_from_vars: '{{ build }}'
        namespace: '{{ ci_cd_namespace }}'
        tags:
          - build
  - object: deploy-dev
    content:
      - name: todolist
        template: '{{ playbook_dir }}/templates/todolist-deploy.yml'
        params_from_vars: '{{ deploy.dev }}'
        namespace: '{{ dev_namespace }}'
        tags:
          - deploy
          - dev
      - name: todolist-db
        template: '{{ playbook_dir }}/templates/mongodb.yml'
        params_from_vars: '{{ db }}'
        namespace: '{{ dev_namespace }}'
        tags:
          - deploy
          - dev
  - object: deploy-test
    content:
      - name: todolist
        template: '{{ playbook_dir }}/templates/todolist-deploy.yml'
        params_from_vars: '{{ deploy.test }}'
        namespace: '{{ test_namespace }}'
        tags:
          - deploy
          - test
      - name: todolist-db
        template: '{{ playbook_dir }}/templates/mongodb.yml'
        params_from_vars: '{{ db }}'
        namespace: '{{ test_namespace }}'
        tags:
          - deploy
          - test
